labels:
  - data_sharing
  - ads
  - third_party_services
  - auto_renewal
  - arbitration
  - account_deletion_restriction
  - location_tracking
  - biometrics
  - no_opt_out
  - user_content_rights
  - gdpr_compliance
  - data_deletion_policy
threshold: 0.7